trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - task: Maven@4
    displayName: 'Build application'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean compile'
      options: '-DskipTests'
  - script: |
      nohup mvn spring-boot:run > app.log 2>&1 &
      echo "Waiting for application startup..."
      sleep 60
    displayName: 'Start Spring Boot'
  - script: |
      cat app.log
      displayName: 'Show Spring Boot Log'  
  - task: Maven@4 
    displayName: 'Run tests'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
  - script: |
      echo "==== APP LOG AFTER TESTS ===="
      cat app.log
      displayName: 'Show application log after tests'
      condition: always()
